local SimpleRandomMount = LibStub("AceAddon-3.0"):NewAddon("SimpleRandomMount")
local group = {}
SLASH_SimpleRandomMount1 = "/srm"
SLASH_SimpleRandomMount2 = "/simplerandommount"

SimpleRandomMount.flying = {
	"Abyss Worm",
	"Aerial Unit R-21/X",
	"Alabaster Stormtalon",
	"Alabaster Thunderwing",
	"Albino Drake",
	"Amani Dragonhawk",
	"Ankoan Waveray",
	"Antoran Charhound",
	"Antoran Gloomhound",
	"Arcanist's Manasaber",
	"Archmage's Prismatic Disc",
	"Argent Hippogryph",
	"Armored Blue Dragonhawk",
	"Armored Blue Wind Rider",
	"Armored Red Dragonhawk",
	"Armored Skyscreamer",
	"Armored Snowy Gryphon",
	"Ashenvale Chimaera",
	"Ashes of Al'ar",
	"Astral Cloud Serpent",
	"Awakened Mindborer",
	"Azshari Bloatray",
	"Azure Cloud Serpent",
	"Azure Drake",
	"Azure Netherwing Drake",
	"Ban-Lu, Grandmaster's Companion",
	"Battlelord's Bloodthirsty War Wyrm",
	"Big Love Rocket",
	"Black Drake",
	"Black Serpent of N'Zoth",
	"Blazing Drake",
	"Blazing Hippogryph",
	"Bloodbathed Frostbrood Vanquisher",
	"Bloodgorged Hunter",
	"Bloodthirsty Dreadwing",
	"Blue Dragonhawk",
	"Blue Drake",
	"Blue Proto-Drake",
	"Blue Riding Nether Ray",
	"Blue Wind Rider",
	"Bronze Drake",
	"Captured Swampstalker",
	"Celestial Steed",
	"Cenarion War Hippogryph",
	"Clutch of Ha-Li",
	"Clutch of Ji-Kun",
	"Cobalt Netherwing Drake",
	"Cobalt Pterrordax",
	"Corrupted Dreadwing",
	"Corrupted Fire Hawk",
	"Corrupted Gladiator's Proto-Drake",
	"Corrupted Hippogryph",
	"Crimson Cloud Serpent",
	"Dark Phoenix",
	"Darkmoon Dirigible",
	"Darkspore Mana Ray",
	"Dazar'alor Windreaver",
	"Deathlord's Vilebrood Vanquisher",
	"Depleted-Kyparium Rocket",
	"Drake of the East Wind",
	"Drake of the Four Winds",
	"Drake of the North Wind",
	"Drake of the South Wind",
	"Drake of the West Wind",
	"Dread Raven",
	"Dusky Waycrest Gryphon",
	"Ebon Gryphon",
	"Eclipse Dragonhawk",
	"Emerald Drake",
	"Enchanted Fey Dragon",
	"Ensorcelled Everwyrm",
	"Expedition Bloodswarmer",
	"Experiment 12-B",
	"Explorer's Jungle Hopper",
	"Farseer's Raging Tempest",
	"Feldrake",
	"Felfire Hawk",
	"Felglow Mana Ray",
	"Felsteel Annihilator",
	"Flameward Hippogryph",
	"Flying Carpet",
	"Flying Machine",
	"Frosty Flying Carpet",
	"G.M.O.D.",
	"Geosynchronous World Spinner",
	"Ghastly Charger",
	"Gold Gladiator's Proto-Drake",
	"Golden Cloud Serpent",
	"Golden Gryphon",
	"Grand Armored Gryphon",
	"Grand Armored Wyvern",
	"Grand Gryphon",
	"Grand Wyvern",
	"Green Gladiator's Proto-Drake",
	"Green Proto-Drake",
	"Green Riding Nether Ray",
	"Green Wind Rider",
	"Grove Defiler",
	"Headless Horseman's Mount",
	"Heart of the Aspects",
	"Hearthsteed",
	"Heavenly Azure Cloud Serpent",
	"Heavenly Crimson Cloud Serpent",
	"Heavenly Golden Cloud Serpent",
	"Heavenly Onyx Cloud Serpent",
	"High Priest's Lightsworn Seeker",
	"Highlord's Golden Charger",
	"Highlord's Valorous Charger",
	"Highlord's Vengeful Charger",
	"Highlord's Vigilant Charger",
	"Hogrus, Swine of Good Fortune",
	"Honeyback Harvester",
	"Huntmaster's Dire Wolfhawk",
	"Huntmaster's Fierce Wolfhawk",
	"Huntmaster's Loyal Wolfhawk",
	"Icebound Frostbrood Vanquisher",
	"Imperial Quilen",
	"Infinite Timereaver",
	"Invincible",
	"Iron Skyreaver",
	"Ironbound Proto-Drake",
	"Ironbound Wraithcharger",
	"Island Thunderscale",
	"Ivory Cloud Serpent",
	"Jade Cloud Serpent",
	"Jade Pandaren Kite",
	"Jade Panther",
	"Jeweled Onyx Panther",
	"Kua'fon",
	"Lambent Mana Ray",
	"Leaping Veinseeker",
	"Leyfeather Hippogryph",
	"Leywoven Flying Carpet",
	"Life-Binder's Handmaiden",
	"Lightforged Warframe",
	"Long-Forgotten Hippogryph",
	"Luminous Starseeker",
	"Magnificent Flying Carpet",
	"Mail Muncher",
	"Malevolent Drone",
	"Mecha-Mogul Mk2",
	"Mechanized Lumber Extractor",
	"Mimiron's Head",
	"Mottled Drake",
	"Mystic Runesaber",
	"Nazjatar Blood Serpent",
	"Netherlord's Accursed Wrathsteed",
	"Netherlord's Brimstone Wrathsteed",
	"Netherlord's Chaotic Wrathsteed",
	"Ny'alotha Allseer",
	"Onyx Cloud Serpent",
	"Onyx Netherwing Drake",
	"Onyxian Drake",
	"Orgrimmar Interceptor",
	"Pale Gladiator's Proto-Drake",
	"Pandaren Kite",
	"Pandaren Kite",
	"Phosphorescent Stone Drake",
	"Plagued Proto-Drake",
	"Priestess' Moonsaber",
	"Proudmoore Sea Scout",
	"Pureblood Fire Hawk",
	"Purple Netherwing Drake",
	"Purple Riding Nether Ray",
	"Rajani Warserpent",
	"Red Dragonhawk",
	"Red Drake",
	"Red Flying Cloud",
	"Red Proto-Drake",
	"Red Riding Nether Ray",
	"Riddler's Mind-Worm",
	"Ruby Panther",
	"Rustbolt Resistor",
	"Rusted Proto-Drake",
	"Sandstone Drake",
	"Sapphire Panther",
	"Scintillating Mana Ray",
	"Shackled Ur'zul",
	"Shadowbarb Drone",
	"Shadowblade's Baneful Omen",
	"Shadowblade's Crimson Omen",
	"Shadowblade's Lethal Omen",
	"Shadowblade's Murderous Omen",
	"Sharkbait",
	"Shu-Zen, the Divine Sentinel",
	"Silent Glider",
	"Siltwing Albatross",
	"Silver Covenant Hippogryph",
	"Silver Riding Nether Ray",
	"Sky Golem",
	"Slayer's Felbroken Shrieker",
	"Smoldering Ember Wyrm",
	"Snowy Gryphon",
	"Soaring Skyterror",
	"Spawn of Galakras",
	"Spectral Pterrorwing",
	"Spirit of Eche'ro",
	"Squawks",
	"Squeakers, the Trickster",
	"Stormsong Coastwatcher",
	"Stormwind Skychaser",
	"Sunreaver Dragonhawk",
	"Sunstone Panther",
	"Swift Blue Gryphon",
	"Swift Green Gryphon",
	"Swift Green Wind Rider",
	"Swift Purple Gryphon",
	"Swift Purple Wind Rider",
	"Swift Red Gryphon",
	"Swift Red Wind Rider",
	"Swift Yellow Wind Rider",
	"Sylverian Dreamer",
	"Tawny Wind Rider",
	"The Dreadwake",
	"The Hivemind",
	"Thundering August Cloud Serpent",
	"Thundering Cobalt Cloud Serpent",
	"Thundering Jade Cloud Serpent",
	"Thundering Onyx Cloud Serpent",
	"Thundering Ruby Cloud Serpent",
	"Time-Lost Proto-Drake",
	"Turbo-Charged Flying Machine",
	"Twilight Avenger",
	"Twilight Drake",
	"Twilight Harbinger",
	"Uncorrupted Voidwing",
	"Unshackled Waveray",
	"Veridian Netherwing Drake",
	"Vibrant Mana Ray",
	"Violet Netherwing Drake",
	"Violet Proto-Drake",
	"Vitreous Stone Drake",
	"Volcanic Stone Drake",
	"Vulpine Familiar",
	"Warforged Nightmare",
	"Waste Marauder",
	"Wastewander Skyterror",
	"Wicked Swarmer",
	"Winged Guardian",
	"Winged Steed of the Ebon Blade",
	"Witherbark Direwing",
	"Wonderwing 2.0",
	"Wriggling Parasite",
	"X-51 Nether-Rocket",
	"X-51 Nether-Rocket X-TREME",
	"Xiwyllag ATV",
	"Yu'lei, Daughter of Jade"
}

SimpleRandomMount.ground = {
	"Acherus Deathcharger",
	"Acid Belcher",
	"Admiralty Stallion",
	"Alabaster Hyena",
	"Amani Battle Bear",
	"Amber Primordial Direhorn",
	"Amber Scorpion",
	"Amethyst Ruinstrider",
	"Arcadian War Turtle",
	"Argent Charger",
	"Argent Warhorse",
	"Armored Brown Bear",
	"Armored Brown Bear",
	"Armored Frostboar",
	"Armored Frostwolf",
	"Armored Irontusk",
	"Armored Razorback",
	"Armored Razzashi Raptor",
	"Ashhide Mushan Beast",
	"Avenging Felcrusher",
	"Azure Riding Crane",
	"Azure Water Strider",
	"Azureshell Krolusk",
	"Beastlord's Irontusk",
	"Beastlord's Warwolf",
	"Beryl Ruinstrider",
	"Big Battle Bear",
	"Big Blizzard Bear",
	"Biletooth Gnasher",
	"Black Battlestrider",
	"Black Dragon Turtle",
	"Black Hawkstrider",
	"Black Primal Raptor",
	"Black Riding Goat",
	"Black Skeletal Horse",
	"Black Stallion",
	"Black War Bear",
	"Black War Bear",
	"Black War Elekk",
	"Black War Kodo",
	"Black War Mammoth",
	"Black War Mammoth",
	"Black War Ram",
	"Black War Raptor",
	"Black War Steed",
	"Black War Tiger",
	"Black War Wolf",
	"Black Wolf",
	"Blackpaw",
	"Blacksteel Battleboar",
	"Bleakhoof Ruinstrider",
	"Blessed Felcrusher",
	"Blonde Riding Yak",
	"Bloodfang Widow",
	"Bloodflank Charger",
	"Bloodgorged Crawg",
	"Bloodhoof Bull",
	"Blue Dragon Turtle",
	"Blue Hawkstrider",
	"Blue Marsh Hopper",
	"Blue Mechanostrider",
	"Blue Qiraji Battle Tank",
	"Blue Shado-Pan Riding Tiger",
	"Blue Skeletal Horse",
	"Bone-White Primal Raptor",
	"Breezestrider Stallion",
	"Brilliant Direbeak",
	"Bristling Hellboar",
	"Broken Highland Mustang",
	"Brown Dragon Turtle",
	"Brown Elekk",
	"Brown Horse",
	"Brown Kodo",
	"Brown Ram",
	"Brown Riding Camel",
	"Brown Riding Goat",
	"Brown Skeletal Horse",
	"Brown Wolf",
	"Bruce",
	"Caravan Hyena",
	"Cerulean Ruinstrider",
	"Champion's Treadblade",
	"Charger",
	"Chauffeured Mechano-Hog",
	"Chauffeured Mekgineer's Chopper",
	"Chestnut Mare",
	"Child of Torcali",
	"Cloudwing Hippogryph",
	"Coalfist Gronnling",
	"Cobalt Primordial Direhorn",
	"Cobalt Riding Talbuk",
	"Cobalt War Talbuk",
	"Conqueror's Scythemaw",
	"Core Hound",
	"Craghorn Chasm-Leaper",
	"Creeping Carpet",
	"Crimson Deathcharger",
	"Crimson Primal Direhorn",
	"Crimson Slavermaw",
	"Crimson Water Strider",
	"Crusader's Direhorn",
	"Dapple Gray",
	"Dark Iron Core Hound",
	"Dark Riding Talbuk",
	"Dark War Talbuk",
	"Darkforge Ram",
	"Darkmoon Dancing Bear",
	"Darkspear Raptor",
	"Darnassian Nightsaber",
	"Dawnforge Ram",
	"Deathtusk Felboar",
	"Deepcoral Snapdragon",
	"Dire Wolf",
	"Domesticated Razorback",
	"Dreadsteed",
	"Dune Scavenger",
	"Dustmane Direwolf",
	"Dusty Rockhide",
	"Elusive Quickhoof",
	"Emerald Raptor",
	"Exarch's Elekk",
	"Exodar Elekk",
	"Explorer's Dunetrekker",
	"Felblaze Infernal",
	"Felsaber",
	"Felsteed",
	"Fiery Warhorse",
	"Flametalon of Alysrazor",
	"Forsaken Warhorse",
	"Fossilized Raptor",
	"Frenzied Feltalon",
	"Frightened Kodo",
	"Frostplains Battleboar",
	"Frostshard Infernal",
	"Frostwolf Howler",
	"Garn Nighthowl",
	"Garn Steelmaw",
	"Giant Coldsnout",
	"Gilded Ravasaur",
	"Glacial Tidestorm",
	"Glorious Felcrusher",
	"Gnomeregan Mechanostrider",
	"Goblin Trike",
	"Goblin Turbo-Trike",
	"Golden King",
	"Golden Primal Direhorn",
	"Golden Riding Crane",
	"Goldenmane",
	"Gorestrider Gronnling",
	"Grand Black War Mammoth",
	"Grand Black War Mammoth",
	"Grand Expedition Yak",
	"Grand Ice Mammoth",
	"Grand Ice Mammoth",
	"Gray Elekk",
	"Gray Kodo",
	"Gray Ram",
	"Great Black Dragon Turtle",
	"Great Blue Dragon Turtle",
	"Great Blue Elekk",
	"Great Brewfest Kodo",
	"Great Brown Dragon Turtle",
	"Great Brown Kodo",
	"Great Exarch's Elekk",
	"Great Golden Kodo",
	"Great Gray Kodo",
	"Great Green Dragon Turtle",
	"Great Green Elekk",
	"Great Greytusk",
	"Great Northern Elderhorn",
	"Great Purple Dragon Turtle",
	"Great Purple Elekk",
	"Great Red Dragon Turtle",
	"Great Red Elekk",
	"Great Sunwalker Kodo",
	"Great White Kodo",
	"Green Dragon Turtle",
	"Green Marsh Hopper",
	"Green Mechanostrider",
	"Green Primal Raptor",
	"Green Qiraji Battle Tank",
	"Green Shado-Pan Riding Tiger",
	"Green Skeletal Warhorse",
	"Grey Riding Camel",
	"Grey Riding Yak",
	"Hellfire Infernal",
	"Highland Mustang",
	"Highmountain Elderhorn",
	"Highmountain Thunderhoof",
	"Ice Mammoth",
	"Ice Mammoth",
	"Illidari Felstalker",
	"Infernal Direwolf",
	"Ironclad Frostclaw",
	"Ironforge Ram",
	"Ironhoof Destroyer",
	"Ironside Warwolf",
	"Ivory Hawkstrider",
	"Jade Primordial Direhorn",
	"Junkheap Drifter",
	"Kaldorei Nightsaber",
	"Kor'kron Annihilator",
	"Kor'kron Juggernaut",
	"Kul Tiran Charger",
	"Lightforged Felcrusher",
	"Lil' Donkey",
	"Llothien Prowler",
	"Lucid Nightmare",
	"Maddened Chaosrunner",
	"Mag'har Direwolf",
	"Magic Rooster",
	"Meat Wagon",
	"Mechacycle Model W",
	"Mechagon Mechanostrider",
	"Mechagon Peacekeeper",
	"Mechano-Hog",
	"Mekgineer's Chopper",
	"Midnight",
	"Mighty Caravan Brutosaur",
	"Minion of Grumpus",
	"Mollie",
	"Mosshide Riverwallow",
	"Mottled Meadowstomper",
	"Mountain Horse",
	"Mudback Riverbeast",
	"Nightborne Manasaber",
	"Obsidian Krolusk",
	"Ochre Skeletal Warhorse",
	"Onyx War Hyena",
	"Orgrimmar Wolf",
	"Pale Thorngrazer",
	"Palehide Direhorn",
	"Pinto",
	"Predatory Bloodgazer",
	"Prestigious Azure Courser",
	"Prestigious Bloodforged Courser",
	"Prestigious Bronze Courser",
	"Prestigious Forest Courser",
	"Prestigious Ivory Courser",
	"Prestigious Midnight Courser",
	"Prestigious Royal Courser",
	"Prestigious War Steed",
	"Prestigious War Wolf",
	"Pureheart Courser",
	"Purple Dragon Turtle",
	"Purple Elekk",
	"Purple Hawkstrider",
	"Purple Skeletal Warhorse",
	"Qinsho's Eternal Hound",
	"Quel'dorei Steed",
	"Ratstallion",
	"Raven Lord",
	"Red Dragon Turtle",
	"Red Hawkstrider",
	"Red Mechanostrider",
	"Red Primal Raptor",
	"Red Qiraji Battle Tank",
	"Red Shado-Pan Riding Tiger",
	"Red Skeletal Horse",
	"Red Skeletal Warhorse",
	"Regal Riding Crane",
	"Ren's Stalwart Hound",
	"Risen Mare",
	"Rivendare's Deathcharger",
	"Rocktusk Battleboar",
	"Royal Snapdragon",
	"Rubyshell Krolusk",
	"Russet Ruinstrider",
	"Rusty Mechanocrawler",
	"Sable Ruinstrider",
	"Sandy Nightsaber",
	"Sapphire Riverbeast",
	"Savage Raptor",
	"Scrapforged Mechaspider",
	"Seabraid Stallion",
	"Shadowhide Pearltusk",
	"Shadowmane Charger",
	"Silver Riding Talbuk",
	"Silver War Talbuk",
	"Silvermoon Hawkstrider",
	"Skullripper",
	"Slate Primordial Direhorn",
	"Smoky Charger",
	"Smoky Direwolf",
	"Snapback Scuttler",
	"Snapdragon Kelpstalker",
	"Snowfeather Hunter",
	"Solar Spirehawk",
	"Son of Galleon",
	"Spawn of Horridon",
	"Spectral Steed",
	"Spectral Tiger",
	"Spectral Wolf",
	"Spotted Frostsaber",
	"Springfur Alpaca",
	"Starcursed Voidstrider",
	"Steelbound Devourer",
	"Stonehide Elderhorn",
	"Stormpike Battle Charger",
	"Stormwind Steed",
	"Striped Dawnsaber",
	"Striped Frostsaber",
	"Striped Nightsaber",
	"Sunhide Gronnling",
	"Sunreaver Hawkstrider",
	"Sunwalker Kodo",
	"Swift Albino Raptor",
	"Swift Blue Raptor",
	"Swift Breezestrider",
	"Swift Brewfest Ram",
	"Swift Brown Ram",
	"Swift Brown Steed",
	"Swift Brown Wolf",
	"Swift Burgundy Wolf",
	"Swift Forest Strider",
	"Swift Frostsaber",
	"Swift Frostwolf",
	"Swift Gray Ram",
	"Swift Gray Steed",
	"Swift Gray Wolf",
	"Swift Green Hawkstrider",
	"Swift Green Mechanostrider",
	"Swift Lovebird",
	"Swift Mistsaber",
	"Swift Moonsaber",
	"Swift Mountain Horse",
	"Swift Olive Raptor",
	"Swift Orange Raptor",
	"Swift Palomino",
	"Swift Pink Hawkstrider",
	"Swift Purple Hawkstrider",
	"Swift Purple Raptor",
	"Swift Razzashi Raptor",
	"Swift Red Hawkstrider",
	"Swift Shorestrider",
	"Swift Spectral Tiger",
	"Swift Springstrider",
	"Swift Stormsaber",
	"Swift Timber Wolf",
	"Swift Violet Ram",
	"Swift Warstrider",
	"Swift White Hawkstrider",
	"Swift White Mechanostrider",
	"Swift White Ram",
	"Swift White Steed",
	"Swift Yellow Mechanostrider",
	"Swift Zulian Panther",
	"Swift Zulian Tiger",
	"Tan Riding Camel",
	"Tan Riding Talbuk",
	"Tan War Talbuk",
	"Terrified Pack Mule",
	"Thalassian Charger",
	"Thalassian Warhorse",
	"Thunder Bluff Kodo",
	"Timber Wolf",
	"Tomb Stalker",
	"Trained Icehoof",
	"Trained Meadowstomper",
	"Trained Riverwallow",
	"Trained Rocktusk",
	"Trained Silverpelt",
	"Trained Snarler",
	"Traveler's Tundra Mammoth",
	"Traveler's Tundra Mammoth",
	"Tundra Icehoof",
	"Turbostrider",
	"Turquoise Raptor",
	"Ultramarine Qiraji Battle Tank",
	"Umber Nightsaber",
	"Umber Ruinstrider",
	"Underrot Crawg",
	"Unpainted Mechanostrider",
	"Valarjar Stormwing",
	"Venomhide Ravasaur",
	"Vicious Black Bonesteed",
	"Vicious Black Warsaber",
	"Vicious Gilnean Warhorse",
	"Vicious Kaldorei Warsaber",
	"Vicious Skeletal Warhorse",
	"Vicious War Basilisk",
	"Vicious War Basilisk",
	"Vicious War Bear",
	"Vicious War Bear",
	"Vicious War Clefthoof",
	"Vicious War Elekk",
	"Vicious War Fox",
	"Vicious War Fox",
	"Vicious War Kodo",
	"Vicious War Lion",
	"Vicious War Mechanostrider",
	"Vicious War Ram",
	"Vicious War Raptor",
	"Vicious War Riverbeast",
	"Vicious War Scorpion",
	"Vicious War Steed",
	"Vicious War Trike",
	"Vicious War Turtle",
	"Vicious War Turtle",
	"Vicious War Wolf",
	"Vicious Warstrider",
	"Vicious White Bonesteed",
	"Vicious White Warsaber",
	"Vile Fiend",
	"Violet Raptor",
	"Viridian Sharptalon",
	"Voidtalon of the Dark Star",
	"Voldunai Dunescraper",
	"Warhorse",
	"Warsong Direfang",
	"White Kodo",
	"White Polar Bear",
	"White Ram",
	"White Riding Camel",
	"White Riding Goat",
	"White Riding Talbuk",
	"White Skeletal Warhorse",
	"White War Talbuk",
	"Wild Dreamrunner",
	"Wild Goretusk",
	"Winterspring Frostsaber",
	"Witherhide Cliffstomper",
	"Wooly Mammoth",
	"Wooly Mammoth",
	"Wooly White Rhino",
	"X-995 Mechanocat",
	"Xinlao",
	"Yellow Marsh Hopper",
	"Yellow Qiraji Battle Tank",
	"Zandalari Direhorn"
}

SimpleRandomMount.aquatic = {
	"Brinedeep Bottom-Feeder",
	"Crimson Tidestallion",
	"Darkwater Skate",
	"Fabious",
	"Fathom Dweller",
	"Great Sea Ray",
	"Inkscale Deepseeker",
	"Pond Nettle",
	"Riding Turtle",
	"Saltwater Seahorse",
	"Sea Turtle",
	"Subdued Seahorse",
	"Surf Jelly",
	"Vashj'ir Seahorse"
}

function SlashCmdList.SimpleRandomMount(msg, editbox)
	if msg == "aquatic" then
		SimpleRandomMount:Mount(SimpleRandomMount.aquatic, table.getn(SimpleRandomMount.aquatic))
	elseif msg == "ground" then
		SimpleRandomMount:Mount(SimpleRandomMount.ground, table.getn(SimpleRandomMount.ground))
	elseif msg == "flying" then
		SimpleRandomMount:Mount(SimpleRandomMount.flying, table.getn(SimpleRandomMount.flying))
	else
		print("Command not found!")
	end
end

function SimpleRandomMount:Mount(mounts, number)
	local rand
	local usable = false
	for i = 1, number do
		if IsUsableSpell(mounts[i]) then
			usable = true
			break
		end
	end
	if usable then
		repeat
			rand = math.random(1, number)
		until IsUsableSpell(mounts[rand])
		CastSpellByName(mounts[rand])
	elseif (mounts == self.fullGround) and IsUsableSpell("Summon Chauffeur") then
		CastSpellByName("Summon Chauffeur")
	end
end
